name: CI/CD

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  infrastructure-deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Install Dependencies
        run: |
          cd frontend
          npm install
          node -v
          npm -v

      - name: Run Build
        run: |
          npm run build

      - name: Run Tests
        run: |
          npm test

      - name: Deploy App
        run: |
          cd ../infrastructure
          npm install
          ENVIRONMENT=dev npm run cdk -- deploy --all --require-approval never
